
```{r, echo=TRUE}

# Loading and preprocessing the data
# Load data from csv file keeping headers
df <- read.csv("./activity.csv", header = TRUE, stringsAsFactors = FALSE)

# Transform text date into Date type class
df$date <- as.Date(df$date)

# Set day of the week in numbers Monday = 1
df$weekday<-as.POSIXlt(df$date)$wday

#======================================


# What is mean total number of steps taken per day?

# Total steps per day
steps.daily <- aggregate(steps  ~ date, data = df, FUN = "sum")
steps.daily.mean <- mean(steps.daily$steps)
steps.daily.median <- median(steps.daily$steps)
hist(steps.daily[,2], main = "Total steps per day", xlab = "Steps", ylab = "Frequency")

# What is the average daily activity pattern?
steps.interval.average <- aggregate(steps  ~ interval, data = df, FUN = "mean")
plot(steps.interval.average$steps,steps.interval.average$inteval, type = "l")
steps.interval.average[which.max( steps.interval.average[,2] ),]

# Imputing missing values
 
# Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs)
length(which(is.na(df)))

# Devise a strategy for filling in all of the missing values in the dataset
# Create a new dataset that is equal to the original dataset but with the missing data filled in.
df1 <- df
df1[which(is.na(df1)),1] <- steps.daily.mean
#*****steps.interval.average[steps.interval.average$interval== df[which(is.na(df)),3] ,2]

#Make a histogram of the total number of steps taken each day and Calculate and report the mean and median
steps.daily.nona <- aggregate(steps  ~ date, data = df1, FUN = "sum")
hist(steps.daily.nona[,2], main = "Total steps per day", xlab = "Steps", ylab = "Frequency")
steps.daily.nona.mean <- mean(steps.daily.nona$steps)
steps.daily.nona.median <- median(steps.daily.nona$steps)

# Set weekday or weekend
steps.daily.nona$wDay <- c('weekend', 'weekday')[(weekdays(steps.daily.nona$date) %in% weekdays1)+1L]
aggregate(steps  ~ date + interval + weekday, data = df1, FUN = "mean")
```

```{r, echo=TRUE}
# What is mean total number of steps taken per day?
aggregate(steps  ~ date, data = df, FUN = "mean")
plot(cars)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
